services:
  - type: web
    name: gemerbarbier-fe
    env: static
    buildCommand: cd gemerbarbier-fe && npm install && npm run build
    staticPublishPath: gemerbarbier-fe/dist
    headers:
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /index.html
        name: Pragma
        value: no-cache
      - path: /index.html
        name: Expires
        value: "0"
      - path: /version.json
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
