openapi: 3.0.3
info:
  title: GemerBarbier API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /barbers:
    get:
      tags: [ Barber ]
      summary: Get all barbers
      operationId: getBarbers
      responses:
        200:
          description: List of barbers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BarberResponse'
  /services:
    get:
      tags: [ CutService ]
      summary: Get all services
      operationId: getCutServices
      responses:
        200:
          description: List of cut services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CutServiceResponse'
  /reservations:
    post:
      tags: [ Reservation ]
      summary: Create reservation (customer)
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationCreateRequest'
      responses:
        200:
          description: Created reservation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationResponse'
  /admin/barbers/{barberId}/time-slots:
    get:
      tags: [ TimeSlotAdmin ]
      summary: Get time slots for barber
      operationId: getTimeSlots
      parameters:
        - $ref: '#/components/parameters/barberIdPath'
        - $ref: '#/components/parameters/date'
      responses:
        200:
          description: List of time slots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeSlotAdminResponse'
        404:
          description: Barber not found
  /admin/barbers/{barberId}/time-slots/deactivate:
    patch:
      tags: [ TimeSlotAdmin ]
      summary: Deactivate all time slots for a specific day
      operationId: deactivateTimeSlots
      parameters:
        - $ref: '#/components/parameters/barberIdPath'
        - $ref: '#/components/parameters/date'
      responses:
        200:
          description: Time slots deactivated
        404:
          description: Barber not found
  /admin/time-slots/{slotId}/status:
    patch:
      tags: [ TimeSlotAdmin ]
      summary: Update time slot statuses
      operationId: updateTimeSlotStatus
      parameters:
        - $ref: '#/components/parameters/timeSlotId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeSlotStatusUpdateRequest'
      responses:
        200:
          description: Updated
  /available-slots:
    get:
      tags: [ TimeSlot ]
      summary: Get available slots for a concrete date, service and barber
      operationId: getAvailableSlots
      parameters:
        - $ref: '#/components/parameters/barberIdQuery'
        - $ref: '#/components/parameters/serviceId'
      responses:
        200:
          description: Available time slots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableTimeSlotResponse'
  /admin/reservations:
    get:
      tags: [ ReservationAdmin ]
      summary: Get reservations for specific day
      operationId: getReservationsByDate
      parameters:
        - $ref: '#/components/parameters/barberIdQuery'
        - $ref: '#/components/parameters/date'
      responses:
        200:
          description: List of reservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationAdminResponse'
    post:
      tags: [ ReservationAdmin ]
      summary: Create reservation by barber (admin)
      operationId: createReservationAsAdmin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationCreateAdminRequest'
      responses:
        201:
          description: Created
  /admin/reservations/{reservationId}/cancel:
    patch:
      tags: [ ReservationAdmin ]
      summary: Cancel reservation
      operationId: cancelReservation
      parameters:
        - $ref: '#/components/parameters/reservationId'
      responses:
        200:
          description: Reservation cancelled
        404:
          description: Reservation not found
        409:
          description: Reservation cannot be cancelled
components:
  parameters:
    barberIdPath:
      name: barberId
      in: path
      required: true
      schema:
        type: integer
        format: int64
    barberIdQuery:
      name: barberId
      in: query
      required: true
      schema:
        type: integer
        format: int64
    serviceId:
      name: serviceId
      in: query
      required: true
      schema:
        type: integer
        format: int64
    timeSlotId:
      name: slotId
      in: path
      required: true
      schema:
        type: integer
        format: int64
    reservationId:
      name: reservationId
      in: path
      required: true
      schema:
        type: integer
        format: int64
    date:
      name: date
      in: query
      required: true
      schema:
        type: string
        format: date
  schemas:
    ReservationAdminResponse:
      type: object
      properties:
        id:
          type: integer
        startTime:
          type: string
          example: "09:00"
        endTime:
          type: string
          example: "09:40"
        customerName:
          type: string
        customerEmail:
          type: string
        customerPhone:
          type: string
        cutServiceName:
          type: string
        note:
          type: string
        status:
          type: string
          enum: [ CREATED, CANCELLED ]
    BarberResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    CutServiceResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        duration:
          type: integer
          format: int32
        price:
          type: integer
          format: int32
    AvailableTimeSlotResponse:
      type: object
      properties:
        date:
          type: string
          format: date
        timeList:
          type: array
          items:
            type: string
    TimeSlotAdminResponse:
      type: object
      properties:
        id:
          type: integer
        startTime:
          type: string
          example: "09:00"
        status:
          type: string
          enum: [ ACTIVE, INACTIVE, RESERVED ]
    TimeSlotCreateRequest:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    TimeSlotStatusUpdateRequest:
      type: object
      required: [ status ]
      properties:
        status:
          type: string
          enum: [ ACTIVE, INACTIVE ]
    ReservationCreateRequest:
      type: object
      required: [ customerName, customerEmail, customerPhone, barberId, serviceId, startTime ]
      properties:
        customerName:
          type: string
        customerEmail:
          type: string
        customerPhone:
          type: string
        barberId:
          type: integer
          format: int64
        serviceId:
          type: integer
          format: int64
        startTime:
          type: string
          format: date-time
    ReservationCreateAdminRequest:
      type: object
      required: [ customerName, barberId, serviceId, startTime ]
      properties:
        customerName:
          type: string
        customerEmail:
          type: string
        customerPhone:
          type: string
        barberId:
          type: integer
          format: int64
        serviceId:
          type: integer
          format: int64
        startTime:
          type: string
          format: date-time
        note:
          type: string
    ReservationResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerName:
          type: string
        barberId:
          type: integer
          format: int64
        serviceId:
          type: integer
          format: int64
        startTime:
          type: string
        endTime:
          type: string
        status:
          type: string
